// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2dJ_zfOo_a7w1v3D7PgBlrC45IplQFMw',
    appId: '1:499148106193:web:661be36b31e11c1dc198f0',
    messagingSenderId: '499148106193',
    projectId: 'movieapp-91a2e',
    authDomain: 'movieapp-91a2e.firebaseapp.com',
    storageBucket: 'movieapp-91a2e.appspot.com',
    measurementId: 'G-CS5LV9LSXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Fn_c7KnRahwWBqHw7iP11OhY0xC4qxY',
    appId: '1:499148106193:android:beb06f774f503f7ec198f0',
    messagingSenderId: '499148106193',
    projectId: 'movieapp-91a2e',
    storageBucket: 'movieapp-91a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyG0uqxRGmWCdZyeiesbbbjzrjIOd8W1g',
    appId: '1:499148106193:ios:4f7395e28b5cc225c198f0',
    messagingSenderId: '499148106193',
    projectId: 'movieapp-91a2e',
    storageBucket: 'movieapp-91a2e.appspot.com',
    iosClientId: '499148106193-i1ucgjv34aomiujurb2i4jjr8hn8pccj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyG0uqxRGmWCdZyeiesbbbjzrjIOd8W1g',
    appId: '1:499148106193:ios:4f7395e28b5cc225c198f0',
    messagingSenderId: '499148106193',
    projectId: 'movieapp-91a2e',
    storageBucket: 'movieapp-91a2e.appspot.com',
    iosClientId: '499148106193-i1ucgjv34aomiujurb2i4jjr8hn8pccj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
